name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write  # Required for changelog updates

jobs:
  cicd:
    uses: Shards-Of-Sapphire/Sapphire-DevOps/.github/workflows/ci-cd-template.yaml@main
    with:
      environment: production  # or staging, dev, etc.
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_WHATSAPP_NUMBER: ${{ secrets.TWILIO_WHATSAPP_NUMBER }}
      TARGET_WHATSAPP_NUMBER: ${{ secrets.TARGET_WHATSAPP_NUMBER }}
